### ISSUE TITLE
About BertAdapterSelfAttention

### ISSUE THREAD

**Issue by Heart-beatsss** [GeneZC/StructBias#2]
你好，我想问一个问题：BertAdapterModel的实现方式有什么特别之处吗？我看与huggingface上面的源码基本一致，尤其是关于self-att计算这块（BertAdapterSelfAttention），这是huggingface上的源码：https://github.com/huggingface/transformers/blob/v4.22.2/src/transformers/models/bert/modeling_bert.py#L333

**Comment by GeneZC** [comment]
主要是加了relative position最大的截断，而且值得注意的是，bert本身并没有调用上述那段代码，只是huggingface留有的接口。

**Comment by Heart-beatsss** [comment]
> 
好的，接口我清楚，我只是好奇这块的代码创新性哈哈哈哈哈

**Comment by Heart-beatsss** [comment]
> 主要是加了relative position最大的截断，而且值得注意的是，bert本身并没有调用上述那段代码，只是huggingface留有的接口。

好的，接口我清楚，我只是好奇这块的代码创新性哈哈哈哈哈

**Comment by GeneZC** [comment]
这块代码确实不新。

**Comment by Heart-beatsss** [comment]
> 这块代码确实不新。

嗯嗯，但整体来说还是很棒的，值得学习！

**Comment by GeneZC** [comment]
I am closing the issue, feel free to reopen it if you have further questions.
