### ISSUE TITLE
About system in use

### ISSUE THREAD

**Issue by loveseola** [GeneZC/StructBias#3]
hello,i was wondering if it can run on windows system python 3.8?thanks!

**Comment by GeneZC** [comment]
Although I have not run the code on Windows, I think there will not be much problem. I suggest you have a try!

**Comment by loveseola** [comment]
> Although I have not run the code on Windows, I think there will not be much problem. I suggest you have a try!

ok,thanks for your answer! i just tried run the run.py yesterday,it's successful
